/listings:
  get:
    operationId: browse
    description: Returns an array of listing objects.
    parameters:
      - name: page
        in: query
        type: string
        default: 1
      - name: limit
        in: query
        type: string
        default: 25
      - name: query
        in: query
        type: string
      - name: with
        in: query
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Listings'
  post:
    description: Creates a new listing.
    parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/Listing'
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Listing'
/listings/{id}:
  get:
    description: Returns a single listing object.
    parameters:
      - name: id
        in: path
        type: string
      - name: with
        in: query
        type: string
        default: key,token
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Listing'
  put:
    description: Updates a single listing object.
    parameters:
      - name: id
        in: path
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/Listing'
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Listing'
  delete:
    description: Deletes a single listing object.
    parameters:
      - name: id
        in: path
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Listing'
