/tokens:
  get:
    description: Returns an array of token objects.
    parameters:
      - name: page
        in: query
        type: string
        default: 1
      - name: limit
        in: query
        type: string
        default: 25
      - name: query
        in: query
        type: string
      - name: with
        in: query
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Tokens'
  post:
    description: Creates a new token.
    parameters:
      - name: body
        in: body
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Token'
/tokens/{id}:
  get:
    description: Returns a single token object.
    parameters:
      - name: id
        in: path
        type: string
      - name: with
        in: query
        type: string
        default: user
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Token'
  put:
    description: Updates a single token object.
    parameters:
      - name: id
        in: path
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/Token'
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Token'
  delete:
    description: Deletes a single token object.
    parameters:
      - name: id
        in: path
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Token'
