/users:
  get:
    operationId: browse
    description: Returns an array of user objects.
    parameters:
      - name: page
        in: query
        type: string
        default: 1
      - name: limit
        in: query
        type: string
        default: 25
      - name: query
        in: query
        type: string
      - name: with
        in: query
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Users'
  post:
    description: Creates a new user.
    parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/User'
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/User'
/users/{id}:
  get:
    description: Returns a single user object.
    parameters:
      - name: id
        in: path
        type: string
      - name: with
        in: query
        type: string
        default: key,token
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/User'
  put:
    description: Updates a single user object.
    parameters:
      - name: id
        in: path
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/User'
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/User'
  delete:
    description: Deletes a single user object.
    parameters:
      - name: id
        in: path
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/User'
