
port: 9000
auth:
  jwt:
    secret: xxx
    algorithim: HS256
mail:
  transport: direct
stripe:
  key: xxx
rethinkdb:
  host: localhost
  port: 28015
  database: sliplife
  username: admin
  password: xxx
  pool: true
  buffer: 1
  max: 1
  silent: true
  timeout: 20
  discovery: false
