/uploads:
  get:
    operationId: browse
    description: Returns an array of upload objects.
    parameters:
      - name: page
        in: query
        type: string
        default: 1
      - name: limit
        in: query
        type: string
        default: 25
      - name: query
        in: query
        type: string
      - name: with
        in: query
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Uploads'
  post:
    description: Creates a new upload.
    parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/Upload'
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Upload'
/uploads/{id}:
  get:
    description: Returns a single upload object.
    parameters:
      - name: id
        in: path
        type: string
      - name: with
        in: query
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Upload'
  put:
    description: Updates a single upload object.
    parameters:
      - name: id
        in: path
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/Tag'
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Upload'
  delete:
    description: Deletes a single upload object.
    parameters:
      - name: id
        in: path
        type: string
    security:
      - jwt: []
    responses:
      200:
        $ref: '#/responses/Upload'
